// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package gnucash

var TableNames = struct {
	Accounts        string
	Billterms       string
	Books           string
	BudgetAmounts   string
	Budgets         string
	Commodities     string
	Customers       string
	Employees       string
	Entries         string
	Invoices        string
	Jobs            string
	Lots            string
	Orders          string
	Prices          string
	Recurrences     string
	Schedxactions   string
	Slots           string
	Splits          string
	TaxtableEntries string
	Taxtables       string
	Transactions    string
	Vendors         string
	Versions        string
}{
	Accounts:        "accounts",
	Billterms:       "billterms",
	Books:           "books",
	BudgetAmounts:   "budget_amounts",
	Budgets:         "budgets",
	Commodities:     "commodities",
	Customers:       "customers",
	Employees:       "employees",
	Entries:         "entries",
	Invoices:        "invoices",
	Jobs:            "jobs",
	Lots:            "lots",
	Orders:          "orders",
	Prices:          "prices",
	Recurrences:     "recurrences",
	Schedxactions:   "schedxactions",
	Slots:           "slots",
	Splits:          "splits",
	TaxtableEntries: "taxtable_entries",
	Taxtables:       "taxtables",
	Transactions:    "transactions",
	Vendors:         "vendors",
	Versions:        "versions",
}
